.TH buffer_putsl 3
.SH NAME
buffer_putsl \- write string list to buffer with separator
.SH SYNOPSIS
.B #include "strlist.h"
.PP
.BI "void buffer_putsl(buffer *" out ", const strlist *" sl ", const char *" separator ");"
.SH DESCRIPTION
.B buffer_putsl
writes the elements of the string list
.I sl
to the buffer
.I out
joined by the string
.IR separator .