.TH strlist_pushb_unique 3
.SH NAME
strlist_pushb_unique \- push buffer to string list if unique
.SH SYNOPSIS
.B #include "strlist.h"
.PP
.BI "int strlist_pushb_unique(strlist *" sl ", const char *" s ", size_t " n ");"
.SH DESCRIPTION
.B strlist_pushb_unique
appends the buffer
.I s
of length
.I n
to the string list
.I sl
only if it is not already present. Returns 1 if added, 0 otherwise.