.TH strlist_contains 3
.SH NAME
strlist_contains \- check if string exists in string list
.SH SYNOPSIS
.B #include "strlist.h"
.PP
.BI "int strlist_contains(const strlist *" sl ", const char *" s ");"
.SH DESCRIPTION
.B strlist_contains
returns 1 if the string
.I s
is present as an element in the string list
.IR sl ,
and 0 otherwise.