.TH strlist_sort 3
.SH NAME
strlist_sort \- sort elements of a string list
.SH SYNOPSIS
.B #include "strlist.h"
.PP
.BI "size_t strlist_sort(strlist *" sl ", strlist_cmpfn_t *" cmp_fn ");"
.SH DESCRIPTION
.B strlist_sort
sorts the elements of the string list
.I sl
in-place. If
.I cmp_fn
is NULL, it defaults to a lexicographical comparison.