.TH strlist_push 3
.SH NAME
strlist_push \- append string to string list
.SH SYNOPSIS
.B #include "strlist.h"
.PP
.BI "int strlist_push(strlist *" sl ", const char *" s ");"
.SH DESCRIPTION
.B strlist_push
appends the null-terminated string
.I s
to the string list
.I sl
using the list's internal separator.