.TH strlist_at_n 3
.SH NAME
strlist_at_n \- get element and length from string list
.SH SYNOPSIS
.B #include "strlist.h"
.PP
.BI "char *strlist_at_n(const strlist *" sl ", size_t " i ", size_t *" n ");"
.SH DESCRIPTION
.B strlist_at_n
returns a pointer to the start of the
.IR i -th
element in the string list
.I sl
and stores its length in
.IR n .