.TH strlist_push_sa 3
.SH NAME
strlist_push_sa \- append stralloc to string list
.SH SYNOPSIS
.B #include "strlist.h"
.PP
.BI "int strlist_push_sa(strlist *" sl ", const stralloc *" sa ");"
.SH DESCRIPTION
.B strlist_push_sa
appends the contents of the stralloc
.I sa
to the string list
.I sl
using the list's internal separator.