.TH strlist_contains_sa 3
.SH NAME
strlist_contains_sa \- check if stralloc exists in string list
.SH SYNOPSIS
.B #include "strlist.h"
.PP
.BI "int strlist_contains_sa(strlist *" sl ", const stralloc *" sa ");"
.SH DESCRIPTION
.B strlist_contains_sa
returns 1 if the contents of
.I sa
are present as an element in the string list
.IR sl ,
and 0 otherwise.