.TH strlist_push_unique 3
.SH NAME
strlist_push_unique \- push string to string list if unique
.SH SYNOPSIS
.B #include "strlist.h"
.PP
.BI "int strlist_push_unique(strlist *" sl ", const char *" s ");"
.SH DESCRIPTION
.B strlist_push_unique
appends the string
.I s
to the string list
.I sl
only if it is not already present. Returns 1 if added, 0 otherwise.