.TH u8s_diff 3 "Version 1.0" "December 2023" "lib/utf8"
.SH NAME
u8s_diff \- Compare two UTF-8 strings
.SH SYNOPSIS
.B #include <lib/utf8.h>
.sp
.BI "int u8s_diff(const char* s1, const char* s2)"
.SH DESCRIPTION
The function .BR u8s_diff () compares two UTF-8 strings. The function takes the following parameters:
.sp
1. The first UTF-8 string to be compared.
2. The second UTF-8 string to be compared.
.sp
The function returns the difference between the two strings.
.SH RETURN VALUE
The function returns the difference between the two strings.
.SH EXAMPLES
No examples are provided for this function.
.SH SEE ALSO
.B u8_to_wc
.SH AUTHOR
This function was written by John Doe.