.TH dlist_length 3
.SH NAME
dlist_length \- count the number of nodes in a doubly-linked list
.SH SYNOPSIS
.B #include "dlist.h"
.PP
.BI "size_t dlist_length(dlist *" l ");"
.SH DESCRIPTION
.B dlist_length
traverses the doubly-linked list
.I l
starting from the head and counts the total number of nodes present.
.SH SEE ALSO
dlist(3)