# Generated by:
#  /c/Users/roman/Desktop/dirlist/build/gcc/Debug/genmakefile -t gcc -m make lib binfmttest.c bsdiffcat.c buffertest.c cc-wrap.c ccat.c cofflist.c compiler-wrapper.c count-depth.c decode-ls-lR.c dnsip.c dnsname.c dnstest.c eagle-gen-cmds.c eagle-init-brd.c eagle-to-circuit.c elf64list.c elflist.c elfwrsec.c genmakefile.c hexedit.c httptest.c impgen.c jsontest.c list-r.c macho32list.c mediathek-list.c mediathek-parser.c msys-shell.c ntldd.c omflist.c opensearch-dump.c pathtool.c pelist.c pkgcfg.c plsconv.c rdir-test.c reg2cmd.c regfilter.c sln.c strarraytest.c torrent-progress.c xmlpp.c xmltest.c xmltest2.c xmltest3.c xmltest4.c ziptest.c tests --debug -o Makefile
CC = gcc
CXX = g++
DEFS = -DDEBUG=1 -DHAVE_ERRNO_H=1
CFLAGS = -g -ggdb
LDFLAGS = -g
AR = gcc-ar
EXTRA_LIBS = -ladvapi32 -lws2_32

all: . .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe .exe
.: . . . . . . binfmttest.c bsdiffcat.c buffertest.c cc-wrap.c ccat.c cofflist.c compiler-wrapper.c count-depth.c decode-ls-lR.c dnsip.c dnsname.c dnstest.c eagle-gen-cmds.c eagle-init-brd.c eagle-to-circuit.c elf64list.c elflist.c elfwrsec.c genmakefile.c hexedit.c httptest.c impgen.c jsontest.c list-r.c macho32list.c mediathek-list.c mediathek-parser.c msys-shell.c ntldd.c omflist.c opensearch-dump.c pathtool.c pelist.c pkgcfg.c plsconv.c rdir-test.c reg2cmd.c regfilter.c sln.c strarraytest.c torrent-progress.c xmlpp.c xmltest.c xmltest2.c xmltest3.c xmltest4.c ziptest.c tests/all_tests.c
	$(CC) $(CFLAGS) $(CPPFLAGS) $(DEFS) -c -o "." .

.exe: . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
	$(CC) $(CFLAGS) $(LDFLAGS) -o .exe . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . $(LIBS) $(EXTRA_LIBS)

clean:
	DEL /F /Q *.
	DEL /F /Q *.exe

