#############################################################################
# Makefile for building: torrent-progress
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sa 21. Feb 02:04:42 2015
# Project:  torrent-progress.pro
# Template: app
# Command: h:/Msys64/MinGW32/local/bin/qmake.exe -o Makefile torrent-progress.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = h:/Msys64/MinGW32/local/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = cp -rf
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: torrent-progress.pro  h:/msys64/mingw32/local/mkspecs/win32-g++/qmake.conf h:/msys64/mingw32/local/mkspecs/features/device_config.prf \
		h:/msys64/mingw32/local/mkspecs/qconfig.pri \
		h:/msys64/mingw32/local/mkspecs/modules/qt_webkit_version.pri \
		h:/msys64/mingw32/local/mkspecs/features/qt_functions.prf \
		h:/msys64/mingw32/local/mkspecs/features/qt_config.prf \
		h:/msys64/mingw32/local/mkspecs/features/exclusive_builds.prf \
		h:/msys64/mingw32/local/mkspecs/features/default_pre.prf \
		h:/msys64/mingw32/local/mkspecs/features/win32/default_pre.prf \
		deployment.pri \
		h:/msys64/mingw32/local/mkspecs/features/debug.prf \
		h:/msys64/mingw32/local/mkspecs/features/debug_and_release.prf \
		h:/msys64/mingw32/local/mkspecs/features/default_post.prf \
		h:/msys64/mingw32/local/mkspecs/features/win32/default_post.prf \
		h:/msys64/mingw32/local/mkspecs/features/win32/console.prf \
		h:/msys64/mingw32/local/mkspecs/features/win32/rtti.prf \
		h:/msys64/mingw32/local/mkspecs/features/win32/exceptions.prf \
		h:/msys64/mingw32/local/mkspecs/features/win32/stl.prf \
		h:/msys64/mingw32/local/mkspecs/features/shared.prf \
		h:/msys64/mingw32/local/mkspecs/features/warn_on.prf \
		h:/msys64/mingw32/local/mkspecs/features/win32/thread_off.prf \
		h:/msys64/mingw32/local/mkspecs/features/resources.prf \
		h:/msys64/mingw32/local/mkspecs/features/uic.prf \
		h:/msys64/mingw32/local/mkspecs/features/yacc.prf \
		h:/msys64/mingw32/local/mkspecs/features/lex.prf \
		h:/msys64/mingw32/local/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile torrent-progress.pro
h:/msys64/mingw32/local/mkspecs/features/device_config.prf:
h:/msys64/mingw32/local/mkspecs/qconfig.pri:
h:/msys64/mingw32/local/mkspecs/modules/qt_webkit_version.pri:
h:/msys64/mingw32/local/mkspecs/features/qt_functions.prf:
h:/msys64/mingw32/local/mkspecs/features/qt_config.prf:
h:/msys64/mingw32/local/mkspecs/features/exclusive_builds.prf:
h:/msys64/mingw32/local/mkspecs/features/default_pre.prf:
h:/msys64/mingw32/local/mkspecs/features/win32/default_pre.prf:
deployment.pri:
h:/msys64/mingw32/local/mkspecs/features/debug.prf:
h:/msys64/mingw32/local/mkspecs/features/debug_and_release.prf:
h:/msys64/mingw32/local/mkspecs/features/default_post.prf:
h:/msys64/mingw32/local/mkspecs/features/win32/default_post.prf:
h:/msys64/mingw32/local/mkspecs/features/win32/console.prf:
h:/msys64/mingw32/local/mkspecs/features/win32/rtti.prf:
h:/msys64/mingw32/local/mkspecs/features/win32/exceptions.prf:
h:/msys64/mingw32/local/mkspecs/features/win32/stl.prf:
h:/msys64/mingw32/local/mkspecs/features/shared.prf:
h:/msys64/mingw32/local/mkspecs/features/warn_on.prf:
h:/msys64/mingw32/local/mkspecs/features/win32/thread_off.prf:
h:/msys64/mingw32/local/mkspecs/features/resources.prf:
h:/msys64/mingw32/local/mkspecs/features/uic.prf:
h:/msys64/mingw32/local/mkspecs/features/yacc.prf:
h:/msys64/mingw32/local/mkspecs/features/lex.prf:
h:/msys64/mingw32/local/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile torrent-progress.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
