.TH array_end 3
.SH NAME
array_end \- return a pointer to the end of an array
.SH SYNTAX
.B #include "array.h"
.LP
void* \fBarray_end\fP(const array* const \fIx\fP);
.SH DESCRIPTION
.B array_end
returns a pointer to the address immediately following the initialized
data in the array \fIx\fP.
.SH SEE ALSO
array(3)