.TH slist_length 3
.SH NAME
slist_length \- count the number of nodes in a singly-linked list
.SH SYNOPSIS
.B #include "slist.h"
.PP
.BI "size_t slist_length(slink **" list ");"
.SH DESCRIPTION
.B slist_length
traverses the singly-linked list pointed to by
.I list
and returns the total count of elements.