.TH slist_unshifts 3
.SH NAME
slist_unshifts \- prepend a string node to a singly-linked list
.SH SYNOPSIS
.B #include "slist.h"
.PP
.BI "int slist_unshifts(slink **" list ", const char *" s ");"
.SH DESCRIPTION
.B slist_unshifts
creates a new node containing a duplicated copy of the string
.I s
and inserts it at the beginning of the singly-linked list
.IR list .
Returns 1 on success, 0 on failure.