.TH fmt_cescape 3
.SH NAME
fmt_cescape \- C-style string escaping
.SH SYNOPSIS
.B #include "textcode.h"
.PP
.BI "size_t fmt_cescape(char *" dest ", const char *" src ", size_t " len ");"
.PP
.BI "size_t fmt_cescape2(char *" dest ", const char *" src ", size_t " len ", const char *" escapeme ");"
.SH DESCRIPTION
.B fmt_cescape
escapes special characters (e.g., newlines, tabs, quotes) in the input string
.I src
of length
.I len
into the buffer
.IR dest ,
following C-style escape conventions.
.B fmt_cescape2
allows additional characters to be escaped by providing them in
.IR escapeme .