.TH stralloc_prepends 3
.SH NAME
stralloc_prepends \- prepend string to stralloc
.SH SYNOPSIS
.B #include "stralloc.h"
.PP
.BI "int stralloc_prepends(stralloc *" sa ", const char *" s ");"
.SH DESCRIPTION
.B stralloc_prepends
prepends the null-terminated string
.I s
to the beginning of the stralloc
.IR sa .