.Dd March 31, 2025
.Dt STRALLOC_CASE_EQUAL 3
.Os
.Sh NAME
.Nm stralloc_case_equal
.Nd compare two stralloc strings case-insensitively for equality
.Sh SYNOPSIS
.In stralloc.h
.Ft size_t
.Fn stralloc_case_equal "const stralloc *sa1" "const stralloc *sa2"
.Sh DESCRIPTION
The
.Fn stralloc_case_equal
function compares the contents of the two dynamic string allocations
.Fa sa1
and
.Fa sa2
case-insensitively.
.Sh RETURN VALUES
Returns non-zero if the two strings are equal ignoring case, or 0 if they differ.
.Sh SEE ALSO
.Xr stralloc_case_diff 3