.TH stralloc_insertb 3
.SH NAME
stralloc_insertb \- insert bytes into a stralloc
.SH SYNTAX
.B #include <stralloc.h>

int stralloc_insertb(stralloc* \fIsa\fP, const char* \fIs\fP, size_t \fIpos\fP, size_t \fIn\fP);
.SH DESCRIPTION
stralloc_insertb inserts \fIn\fP bytes from \fIs\fP into the stralloc \fIsa\fP at
position \fIpos\fP. If \fIpos\fP is greater than or equal to the current length of \fIsa\fP,
it behaves like stralloc_catb. Otherwise, it moves existing data to accommodate the
new bytes.
.SH RETURN VALUE
1 if successful, 0 if memory allocation failed.
.SH SEE ALSO
stralloc_catb(3)