.Dd March 31, 2025
.Dt STRALLOC_DECAMELIZE 3
.Os
.Sh NAME
.Nm stralloc_decamelize
.Nd convert camelCase to separated lowercase words
.Sh SYNOPSIS
.In stralloc.h
.Ft size_t
.Fn stralloc_decamelize "const char *s" "stralloc *sa" "char sep"
.Sh DESCRIPTION
The
.Fn stralloc_decamelize
function converts a camelCase or PascalCase null-terminated string
.Fa s
into a lower-case string separated by
.Fa sep
characters, appending the result into
.Fa sa .
.Sh RETURN VALUES
Returns the total length of the resulting string in
.Fa sa .