.TH stralloc_diffb 3
.SH NAME
stralloc_diffb \- compare stralloc with a buffer
.SH SYNOPSIS
.B #include "stralloc.h"
.PP
.BI "int stralloc_diffb(const stralloc *" sa ", const void *" d ", unsigned int " dlen ");"
.SH DESCRIPTION
.B stralloc_diffb
compares the contents of the stralloc
.I sa
with the buffer
.I d
of length
.IR dlen .
It returns an integer less than, equal to, or greater than zero, if
.I sa
is lexicographically less than, equal to, or greater than the buffer
.IR d .