.Dd March 31, 2025
.Dt STRALLOC_CATM_INTERNAL 3
.Os
.Sh NAME
.Nm stralloc_catm_internal
.Nd append multiple null-terminated strings to a stralloc
.Sh SYNOPSIS
.In stralloc.h
.Ft int
.Fn stralloc_catm_internal "stralloc *sa" "..."
.Sh DESCRIPTION
The
.Fn stralloc_catm_internal
function takes a
.Dv NULL -terminated
list of string pointers and appends each string sequentially to the dynamic string
.Fa sa .
.Sh RETURN VALUES
Returns 1 on success, or 0 on memory allocation failure.
.Sh SEE ALSO
.Xr stralloc_cats 3