.TH stralloc_findb 3
.SH NAME
stralloc_findb \- find buffer in stralloc
.SH SYNOPSIS
.B #include "stralloc.h"
.PP
.BI "size_t stralloc_findb(const stralloc *" sa ", const void *" what ", size_t " len ");"
.SH DESCRIPTION
.B stralloc_findb
searches for the first occurrence of the buffer
.I what
of length
.I len
within the stralloc
.IR sa .
It returns the index of the start of the match, or
.B sa->len
if not found.