.TH stralloc_catwcb 3 "Version 1.0" "December 2023" "lib/stralloc"
.SH NAME
stralloc_catwcb \- Append a wide character string to a string allocation
.SH SYNOPSIS
.B #include <lib/stralloc.h>
.B #include <lib/byte.h>
.B #include <lib/utf8.h>
.sp
.BI "int stralloc_catwcb(stralloc* sa, const wchar_t* x, size_t n)"
.SH DESCRIPTION
The function .BR stralloc_catwcb () appends a wide character string to a string allocation. The function takes the following parameters:
.sp
1. A pointer to a string allocation structure.
2. A pointer to the wide character string.
3. The number of wide characters to append.
.sp
The function appends the wide character string to the string allocation.
.SH RETURN VALUE
1 if the function succeeds, 0 if it runs out of memory.
.SH EXAMPLES
No examples are provided for this function.
.SH SEE ALSO
.B stralloc_cat, stralloc_catulong0, stralloc_zero
.SH AUTHOR
This function was written by John Doe.