.TH stralloc_replaces 3
.SH NAME
stralloc_replaces \- replace substring in stralloc
.SH SYNOPSIS
.B #include "stralloc.h"
.PP
.BI "int stralloc_replaces(stralloc *" sa ", const char *" from ", const char *" to ");"
.SH DESCRIPTION
.B stralloc_replaces
replaces all occurrences of the null-terminated string
.I from
with the string
.I to
within the stralloc
.IR sa .