.TH stralloc_replacec 3
.SH NAME
stralloc_replacec \- replace character in stralloc
.SH SYNOPSIS
.B #include "stralloc.h"
.PP
.BI "void stralloc_replacec(stralloc *" sa ", char " before ", char " after ");"
.SH DESCRIPTION
.B stralloc_replacec
replaces all occurrences of the character
.I before
with the character
.I after
in the stralloc
.IR sa .