.TH stralloc_remove 3
.SH NAME
stralloc_remove \- remove bytes from a stralloc
.SH SYNTAX
.B #include <stralloc.h>

size_t stralloc_remove(stralloc* \fIsa\fP, size_t \fIpos\fP, size_t \fIn\fP);
.SH DESCRIPTION
stralloc_remove removes \fIn\fP bytes starting at \fIpos\fP from the stralloc \fIsa\fP.
It shifts subsequent data in the stralloc to fill the gap.
.SH RETURN VALUE
The number of bytes removed. Returns -1 if \fIpos\fP is out of bounds.