.TH stralloc_catc 3
.SH NAME
stralloc_catc \- append a character to a stralloc
.SH SYNTAX
.B #include <stralloc.h>

int stralloc_catc(stralloc* \fIsa\fP, const unsigned char \fIc\fP);
.SH DESCRIPTION
stralloc_catc appends the byte \fIc\fP to the end of the stralloc \fIsa\fP.
It handles memory allocation automatically, ensuring there is enough space.
.SH RETURN VALUE
1 if successful, 0 if memory allocation failed.
.SH SEE ALSO
stralloc_catb(3)