.TH stralloc_move 3
.SH NAME
stralloc_move, stralloc_moveb \- move data between stralloc structures
.SH SYNTAX
.B #include <stralloc.h>

void stralloc_move(stralloc* \fIto\fP, stralloc* \fIfrom\fP);
char* stralloc_moveb(stralloc* \fIfrom\fP, size_t* \fIlen\fP);
.SH DESCRIPTION
stralloc_move transfers ownership of the string buffer from \fIfrom\fP to \fIto\fP,
reinitializing \fIfrom\fP to empty.
stralloc_moveb releases ownership of the underlying buffer in \fIfrom\fP and
returns a pointer to it, setting \fIlen\fP to the current length of the string.
The caller is responsible for freeing the returned pointer.