.Dd March 31, 2025
.Dt STRALLOC_CONTAINS 3
.Os
.Sh NAME
.Nm stralloc_contains
.Nd check if a stralloc contains a substring
.Sh SYNOPSIS
.In stralloc.h
.Ft int
.Fn stralloc_contains "const stralloc *sa" "const char *what"
.Sh DESCRIPTION
The
.Fn stralloc_contains
function checks whether the null-terminated substring
.Fa what
exists within the dynamic string
.Fa sa .
.Sh RETURN VALUES
Returns non-zero if the substring is found, or 0 otherwise.
.Sh SEE ALSO
.Xr stralloc_finds 3