.TH stralloc_fmt_pred 3
.SH NAME
stralloc_fmt_pred \- format stralloc with predicate
.SH SYNOPSIS
.B #include "stralloc.h"
.PP
.BI "size_t stralloc_fmt_pred(stralloc *" out ", const char *" in ", size_t " in_len ", size_t (*" fn ")(char*, int), int (*" pred ")(int));"
.SH DESCRIPTION
.B stralloc_fmt_pred
processes each character of the input buffer
.I in
of length
.I in_len
through a predicate
.IR pred .
If
.I pred
is true, the formatting function
.I fn
is called; otherwise, the character is copied verbatim to
.IR out .