.Dd March 31, 2025
.Dt STRALLOC_CASE_EQUALS 3
.Os
.Sh NAME
.Nm stralloc_case_equals
.Nd compare a stralloc and a null-terminated string case-insensitively for equality
.Sh SYNOPSIS
.In stralloc.h
.Ft size_t
.Fn stralloc_case_equals "const stralloc *sa" "const char *s"
.Sh DESCRIPTION
The
.Fn stralloc_case_equals
function compares the contents of the dynamic string
.Fa sa
against the null-terminated C-string
.Fa s
case-insensitively.
.Sh RETURN VALUES
Returns non-zero if the two strings are equal ignoring case, or 0 if they differ.
.Sh SEE ALSO
.Xr stralloc_case_equal 3 ,
.Xr stralloc_case_diffs 3