.TH STRALLOC_CATINT 3 "2023-10-15" "c-utils" "String Allocation Functions"
.SH NAME
 stralloc_catint \- Append an integer to a string
.SH LIBRARY
 libstralloc
.SH SYNOPSIS
 .B #include <stralloc/stralloc.h>

 .B void
 stralloc_catint(stralloc *sa, int val);
.SH DESCRIPTION
 Appends the integer val to the string allocation object sa as a decimal
 string. This function is used for converting integers to strings in the
 c-utils library.
.SH RETURN VALUES
 None. Errors are reported via standard I/O or logging mechanisms.
.SH SEE ALSO
 stralloc_catint0(3), stralloc_catuint(3)
.SH AUTHORS
 Written by the c-utils development team.