.TH str_end 3
.SH NAME
str_end \- check if a string ends with a suffix
.SH SYNOPSIS
.B #include "str.h"
.PP
.BI "int str_end(const char *" a ", const char *" b ");"
.SH DESCRIPTION
.B str_end
checks if string
.I b
is a suffix of string
.IR a .
It returns 1 if
.I b
is a suffix of
.IR a ,
and 0 otherwise.
.SH SEE ALSO
str_endb(3)