.TH HMAP_SET_STRALLOC 3 "15 Mar 2023" "CB" "Library Functions"

.SH NAME
hmap_set_stralloc \- Set a string value in a hash map using stralloc

.SH SYNOPSIS
.IB #include <lib/hmap.h>

.IB int
.IB hmap_set_stralloc(HMAP_DB** hmap_db, const stralloc* key, const stralloc* data);

.SH DESCRIPTION
The \fBhmap_set_stralloc\fR function sets a string value in a hash map using the \fBstralloc\fR data structure. It takes a double pointer to the hash map database, a key \fBstralloc\fR, and a data \fBstralloc\fR as arguments.

The function takes the following parameters:
.IB HMAP_DB**
.IB hmap_db
A double pointer to the hash map database.

.IB const stralloc*
.IB key
A pointer to the key \fBstralloc\fR.

.IB const stralloc*
.IB data
A pointer to the data \fBstralloc\fR.

The function returns an integer indicating the success or failure of the operation. Possible return values include:
.IB HMAP_SUCCESS
The string value was successfully set in the hash map.
.IB HMAP_FAILURE
The string value could not be set in the hash map.

The \fBhmap_set_stralloc\fR function is intended to be used to set a string value in a hash map using the \fBstralloc\fR data structure. It internally uses the \fBhmap_add\fR function to add the key-value pair to the hash map.

.SH EXAMPLES
The following example demonstrates how to use the \fBhmap_set_stralloc\fR function to set a string value in a hash map:

.nf
#include <stdio.h>
#include <lib/hmap.h>
#include <lib/stralloc.h>

int main() {
    HMAP_DB* hmap_db = 0;
    stralloc key = stralloc_zero;
    stralloc data = stralloc_zero;

    // Initialize the hash map database
    hmap_init(&hmap_db);

    // Initialize key and data
    stralloc_copyb(&key, "example1");
    stralloc_copyb(&data, "data1");

    // Set a string value in the hash map
    int result = hmap_set_stralloc(&hmap_db, &key, &data);

    if(result == HMAP_SUCCESS) {
        printf("String value set successfully\n");
    } else {
        printf("Failed to set string value\n");
    }

    // Free the hash map database
    hmap_destroy(&hmap_db);

    return 0;
}
.nef