.TH SOCKET_IP4LOOPBACK 3 "15 Mar 2023" "CB" "Library Functions"

.SH NAME
socket_ip4loopback \- Get the IPv4 loopback address

.SH SYNOPSIS
.IB #include <lib/socket.h>

.IB const char*
.IB socket_ip4loopback(void);

.SH DESCRIPTION
The \fBsocket_ip4loopback\fR function is used to get the IPv4 loopback address.

.SH RETURN VALUE
The \fBsocket_ip4loopback\fR function returns a pointer to the IPv4 loopback address.

.SH EXAMPLES
The following example demonstrates how to use the \fBsocket_ip4loopback\fR function:

.nf
#include <stdio.h>
#include <lib/socket.h>

int main() {
    const char* ip4loopback = socket_ip4loopback();

    printf("IPv4 Loopback Address: %s\n", ip4loopback);

    return 0;
}
.nef