.TH BUFFER_0SMALL 3 "15 Mar 2023" "CB" "Library Functions"

.SH NAME
buffer_0small \- Initialize a small buffer for reading from a file descriptor

.SH SYNOPSIS
.IB #include <lib/buffer.h>

.IB buffer*
.IB buffer_0small;

.SH DESCRIPTION
The \fBbuffer_0small\fR buffer is initialized for reading from a file descriptor. It uses a static buffer \fBbuffer_0small_space\fR with a size of 128 bytes for storing the read data.

The \fBbuffer_0small\fR buffer is intended for use with the \fBbuffer_1small\fR buffer, which is used for writing. The \fBbuffer_flush\fR function is called before reading to ensure that any data in \fBbuffer_1small\fR is written out.

The \fBbuffer_0small\fR buffer is a static buffer and is initialized automatically when the library is loaded.

.SH EXAMPLES
The following example demonstrates how to use the \fBbuffer_0small\fR buffer to read data from a file descriptor:

.nf
#include <stdio.h>
#include <lib/buffer.h>

int main() {
    fd_type fd = open("example.txt", O_RDONLY);
    if(fd < 0) {
        perror("open");
        return 1;
    }

    char data[128];
    ssize_t n = buffer_read(buffer_0small, data, sizeof data);
    if(n < 0) {
        perror("buffer_read");
        close(fd);
        return 1;
    }

    printf("Data: %.*s\n", (int)n, data);

    close(fd);
    return 0;
}
.nef