.TH buffer_putuint64 3
.SH NAME
buffer_putuint64 \- write a decimal ASCII representation of a signed
long integer to buffer
.SH SYNTAX
.B #include <buffer.h>

int \fBbuffer_putuint64\fP(buffer* \fIb\fR,uint64 \fIx\fR);
.SH DESCRIPTION
buffer_putuint64 is equivalent to passing the result of fmt_uint64 to
buffer_put.
.SH "RETURN VALUE"
0 if everything is fine, -1 on error (setting \fIerrno\fR).
.SH "SEE ALSO"
fmt_uint64(3), buffer_put(3), buffer_flush(3), buffer(3)
