.TH IO_ADDBUF 3 "15 Mar 2023" "CB" "Library Functions"

.SH NAME
iob_addbuf \- Add data to an I/O batch buffer

.SH SYNOPSIS
.IB #include <lib/iob_internal.h>

.IB int
.IB iob_addbuf(
.IB io_batch* b,
.IB const void* buf,
.IB uint64 n
.IB );

.SH DESCRIPTION
The \fBiob_addbuf\fR function adds data from a buffer to an I/O batch buffer. This function is an interface to the internal function \fBiob_addbuf_internal\fR, which performs the actual operation.

The function takes the following parameters:

.IB b
Pointer to the I/O batch buffer.

.IB buf
Pointer to the buffer containing the data to be added.

.IB n
Number of bytes to add from the buffer.

The function returns 0 on success, or a negative value indicating an error.

The function is part of the \fBiob\fR library, which provides a framework for managing I/O operations in batch mode.

.SH EXAMPLES
The following example demonstrates how to use the \fBiob_addbuf\fR function to add data to an I/O batch buffer:

.nf
#include <stdio.h>
#include <lib/iob_internal.h>

int main() {
  io_batch batch;

  if (iob_init(&batch) != 0) {
    perror("iob_init");
    return 1;
  }

  const char* data = "Hello, World!";
  uint64 data_size = strlen(data);

  if (iob_addbuf(&batch, data, data_size) != 0) {
    perror("iob_addbuf");
    iob_free(&batch);
    return 1;
  }

  if (iob_execute(&batch) != 0) {
    perror("iob_execute");
    iob_free(&batch);
    return 1;
  }

  printf("Data added to batch buffer\n");

  iob_free(&batch);
  return 0;
}
.nef