.TH OMF_NEXT 3 "OMF Format" "LIBOMF" "Library Functions"
.SH NAME
omf_next - Get the next record in an OMF file
.SH SYNOPSIS
.B #include <lib/omf/omf.h>
.PP
.B omf_record* omf_next(omf_record* rec);
.SH DESCRIPTION
The
.B omf_next
function returns a pointer to the next record in an OMF file.
This pointer can be used to iterate over the records in the file.
.SH ARGUMENTS
.TP
.I rec
A pointer to an
.B omf_record
structure representing the current record.
.SH RETURN VALUE
A pointer to the next record in the OMF file.
.SH EXAMPLE
The following example demonstrates how to use the
.B omf_next
function:
.PP
.B #include <lib/omf/omf.h>
.B #include <stdio.h>
.PP
.B int main() {
.B \tomf_file omf;
.B \tomf_record* rec = omf_read(&omf);
.B \twhile(rec != NULL) {
.B \tprintf("Record type: %d\n", rec->type);
.B \trec = omf_next(rec);
.B \t}
.B \treturn 0;
.B }
.SH SEE ALSO
.B omf_init,
.B omf_read,
.B omf_record