.TH taia_half 3
.SH NAME
taia_half \- divide a TAI64NA time value by two
.SH SYNTAX
.B #include "taia.h"
.LP
void \fBtaia_half\fP(tai6464* \fIt\fP, const tai6464* \fIu\fP);
.SH DESCRIPTION
.B taia_half
divides the TAI64NA time value \fIu\fP by 2 and stores the result in \fIt\fP.
.SH SEE ALSO
taia(3)