.TH http_response_read 3 "HTTP Library Functions" "QuickJS" "HTTP Library Functions"

.SH NAME
http_response_read \- Read data from an HTTP response

.SH SYNOPSIS
.B #include <lib/http.h>
.B ssize_t http_response_read(buffer* in, http_response* response);

.SH DESCRIPTION
The .B http_response_read function reads data from an HTTP response.

The function takes two parameters:
.I in
The input buffer.
.I response
The HTTP response structure.

The function returns the number of bytes read, or -1 on error.

.SH EXAMPLE
The following example demonstrates how to use the .B http_response_read function:

.I
.nf
#include <stdio.h>
#include <lib/http.h>
#include <buffer.h>

int main() {
  // Assume in is a valid input buffer and response is a valid HTTP response structure
  buffer in;
  http_response response;

  // Initialize in and response

  ssize_t bytes_read = http_response_read(&in, &response);

  if (bytes_read < 0) {
    perror("http_response_read");
    return 1;
  }

  // Use the data read

  return 0;
}
.!
.SH "SEE ALSO"
http_connect(3)