.TH gpio_set_input_resistor_pull 3 "Version 1.0" "December 2023" "lib/gpio"
.SH NAME
gpio_set_input_resistor_pull \- Set the input resistor pull mode of a GPIO pin
.SH SYNOPSIS
.B #include <lib/gpio.h>
.B #include <lib/gpio_internal.h>
.sp
.BI "void gpio_set_input_resistor_pull(int const pin_nr, int const pull)"
.SH DESCRIPTION
The function .BR gpio_set_input_resistor_pull () sets the input resistor pull mode of the specified GPIO pin. The function takes the following parameters:
.sp
1. The number of the GPIO pin.
2. The pull mode to be set (e.g., GPIO_PULL_DOWN, GPIO_PULL_UP).
.sp
The function first sets the GPIO pin mode to GPIO_INPUT and then sets the input resistor pull mode to the specified value.
.SH RETURN VALUE
None.
.SH EXAMPLES
No examples are provided for this function.
.SH SEE ALSO
.B gpio_init, gpio_read, gpio_write
.SH AUTHOR
This function was written by John Doe.