.TH gpio_short_wait 3 "Version 1.0" "December 2023" "lib/gpio"
.SH NAME
gpio_short_wait \- Perform a short wait
.SH SYNOPSIS
.B #include <lib/gpio.h>
.B #include <lib/gpio_internal.h>
.sp
.BI "void gpio_short_wait(void)"
.SH DESCRIPTION
The function .BR gpio_short_wait () performs a short wait. The wait duration is platform-specific.
.SH RETURN VALUE
None.
.SH EXAMPLES
No examples are provided for this function.
.SH SEE ALSO
.B gpio_init, gpio_read, gpio_write
.SH AUTHOR
This function was written by John Doe.