.TH gpio_set_pin_mode 3 "Version 1.0" "December 2023" "lib/gpio"
.SH NAME
gpio_set_pin_mode \- Set the mode of a GPIO pin
.SH SYNOPSIS
.B #include <lib/gpio.h>
.B #include <lib/gpio_internal.h>
.sp
.BI "void gpio_set_pin_mode(int const pin_nr, int const mode)"
.SH DESCRIPTION
The function .BR gpio_set_pin_mode () sets the mode of the specified GPIO pin. The function takes the following parameters:
.sp
1. The number of the GPIO pin.
2. The mode to be set (e.g., GPIO_INPUT, GPIO_OUTPUT).
.sp
The function sets the GPIO pin mode to the specified value.
.SH RETURN VALUE
None.
.SH EXAMPLES
No examples are provided for this function.
.SH SEE ALSO
.B gpio_init, gpio_read, gpio_write
.SH AUTHOR
This function was written by John Doe.