.TH cpp_define 3
.SH NAME
cpp_define \- define preprocessor macro
.SH SYNTAX
.B #include "cpp.h"

void \fBcpp_define\fP(cpp_ctx* \fIpp\fR, char* \fIname\fR, char* \fIbuf\fR);
.SH DESCRIPTION
\fBcpp_define\fP defines a preprocessor macro named \fIname\fR with definition
body or value \fIbuf\fR in the preprocessor context \fIpp\fR.

It constructs a temporary virtual source file containing the macro definition,
tokenizes it, reads the macro definition into \fIpp\fR, and cleans up temporary
tokens and resources.
.SH "SEE ALSO"
cpp_init(3), cpp_init_macros(3), cpp_undefine(3)