.TH cpp_init_macros 3
.SH NAME
cpp_init_macros \- define predefined system and builtin macros
.SH SYNTAX
.B #include "cpp.h"

void \fBcpp_init_macros\fP(cpp_ctx* \fIpp\fR);
.SH DESCRIPTION
\fBcpp_init_macros\fP registers predefined GNU target macros, predefined build time macros (\fI__DATE__\fR and \fI__TIME__\fR), and special builtin macro callbacks (\fI__FILE__\fR, \fI__LINE__\fR, \fI__COUNTER__\fR, \fI__TIMESTAMP__\fR, and \fI__BASE_FILE__\fR) into the preprocessor context \fIpp\fR.
.SH "SEE ALSO"
cpp_init(3), cpp_define(3)