.TH iarray_length 3
.SH NAME
iarray_length \- return the number of elements in an iarray
.SH SYNTAX
.B #include "iarray.h"
.LP
size_t \fBiarray_length\fP(iarray* \fIia\fP);
.SH DESCRIPTION
.B iarray_length
returns the number of elements currently stored in the iarray \fIia\fP.
.SH SEE ALSO
iarray(3)