.TH tokenizer_skip_until 3 "Version 1.0" "December 2023" "lib/tokenizer"
.SH NAME
tokenizer_skip_until \- Skip input until a specific marker is encountered
.SH SYNOPSIS
.B #include <lib/tokenizer.h>
.sp
.BI "void tokenizer_skip_until(tokenizer* t, const char* marker)"
.SH DESCRIPTION
The function .BR tokenizer_skip_until () skips input until a specific marker is encountered. The function takes the following parameters:
.sp
1. A pointer to the tokenizer.
2. A string representing the marker.
.sp
The function does not return a value.
.SH RETURN VALUE
No return value.
.SH EXAMPLES
No examples are provided for this function.
.SH SEE ALSO
.B tokenizer
.SH AUTHOR
This function was written by John Doe.