.TH tokenizer_set_flags 3 "Version 1.0" "December 2023" "lib/tokenizer"
.SH NAME
tokenizer_set_flags \- Set the flags of a tokenizer
.SH SYNOPSIS
.B #include <lib/tokenizer.h>
.sp
.BI "void tokenizer_set_flags(tokenizer* t, int flags)"
.SH DESCRIPTION
The function .BR tokenizer_set_flags () sets the flags of a tokenizer. The function takes the following parameters:
.sp
1. A pointer to the tokenizer.
2. An int value representing the flags.
.sp
The function does not return a value.
.SH RETURN VALUE
No return value.
.SH EXAMPLES
No examples are provided for this function.
.SH SEE ALSO
.B tokenizer
.SH AUTHOR
This function was written by John Doe.