.TH tokenizer_ftello 3 "Version 1.0" "December 2023" "lib/tokenizer"
.SH NAME
tokenizer_ftello \- Get the current position in a tokenizer's input
.SH SYNOPSIS
.B #include <lib/tokenizer.h>
.sp
.BI "int64 tokenizer_ftello(tokenizer* t)"
.SH DESCRIPTION
The function .BR tokenizer_ftello () retrieves the current position in a tokenizer's input. The function takes the following parameter:
.sp
1. A pointer to the tokenizer.
.sp
The function returns the current position as an int64 value.
.SH RETURN VALUE
The current position as an int64 value.
.SH EXAMPLES
No examples are provided for this function.
.SH SEE ALSO
.B tokenizer
.SH AUTHOR
This function was written by John Doe.