.TH tokentype_to_str 3 "Version 1.0" "December 2023" "lib/tokenizer"
.SH NAME
tokentype_to_str \- Convert a tokentype enum to a string
.SH SYNOPSIS
.B #include <lib/tokenizer.h>
.sp
.BI "const char* tokentype_to_str(enum tokentype tt)"
.SH DESCRIPTION
The function .BR tokentype_to_str () converts a tokentype enum to a string representation. The function takes the following parameter:
.sp
1. An enum tokentype value.
.sp
The function returns a string representing the tokentype.
.SH RETURN VALUE
A string representing the tokentype.
.SH EXAMPLES
No examples are provided for this function.
.SH SEE ALSO
.B tokentype
.SH AUTHOR
This function was written by John Doe.