.TH tokenizer_skip_chars 3
.SH NAME
tokenizer_skip_chars \- skip a set of characters
.SH SYNOPSIS
.B #include "tokenizer.h"
.PP
.BI "int tokenizer_skip_chars(tokenizer *" t ", const char *" chars ", int *" count ");"
.SH DESCRIPTION
.B tokenizer_skip_chars
advances the tokenizer position past any characters found in the string
.IR chars .
The number of characters skipped is stored in
.IR count .