.TH tokenizer_rewind 3
.SH NAME
tokenizer_rewind \- reset tokenizer to start of input
.SH SYNOPSIS
.B #include "tokenizer.h"
.PP
.BI "int tokenizer_rewind(tokenizer *" t ");"
.SH DESCRIPTION
.B tokenizer_rewind
resets the tokenizer
.I t
to the beginning of the input stream, allowing re-parsing of the same content.