.TH tokenizer_set_filename 3
.SH NAME
tokenizer_set_filename \- set filename for tokenizer
.SH SYNOPSIS
.B #include "tokenizer.h"
.PP
.BI "void tokenizer_set_filename(tokenizer *" t ", const char *" fn ");"
.SH DESCRIPTION
.B tokenizer_set_filename
associates the filename
.I fn
with the tokenizer
.I t
for use in error reporting or debugging.