.TH tokenizer_next 3
.SH NAME
tokenizer_next \- retrieve next token
.SH SYNOPSIS
.B #include "tokenizer.h"
.PP
.BI "int tokenizer_next(tokenizer *" t ", token *" out ");"
.SH DESCRIPTION
.B tokenizer_next
parses the next token from the input stream associated with the tokenizer
.I t
and stores the results in the
.I out
structure. Returns 1 if a token was successfully parsed, 0 otherwise.