.TH scan_uint64 3
.SH NAME
scan_uint64 \- parse an unsigned long integer in decimal ASCII representation
.SH SYNTAX
.B #include <scan.h>

size_t \fBscan_uint64\fP(const char *\fIsrc\fR,uint64 *\fIdest\fR);
.SH DESCRIPTION
scan_uint64 parses an uint64eger in decimal ASCII representation
from \fIsrc\fR and writes the result into \fIdest\fR. It returns the
number of bytes read from \fIsrc\fR.
.SH "SEE ALSO"
scan_int64(3), fmt_uint64(3)
