.TH uint32_prng 3
.SH NAME
uint32_prng \- pseudo-random number generator
.SH SYNTAX
.B #include "uint32.h"
.LP
uint32 \fBuint32_prng\fP(uint32 \fIvalue\fP, uint32 \fIseed\fP);
.SH DESCRIPTION
.B uint32_prng
generates a pseudo-random 32-bit integer based on the provided \fIvalue\fP
and \fIseed\fP.
.SH SEE ALSO
uint32(3)