.TH uint32_read 3
.SH NAME
uint32_read \- read a little-endian 32-bit integer
.SH SYNTAX
.B #include "uint32.h"
.LP
uint32 \fBuint32_read\fP(const char* \fIin\fP);
.SH DESCRIPTION
.B uint32_read
reads four bytes from the memory pointed to by \fIin\fP and interprets them
as a little-endian 32-bit unsigned integer.
.SH SEE ALSO
uint32(3)