.TH FMT_ESCAPECHARSHELL 3 "15 Mar 2023" "CB" "Library Functions"

.SH NAME
fmt_escapecharshell \- Escape characters for shell format

.SH SYNOPSIS
.IB #include <lib/fmt.h>

.IB size_t
.IB fmt_escapecharshell(char* dest, int chr);

.SH DESCRIPTION
The \fBfmt_escapecharshell\fR function escapes characters for shell format. It takes a destination buffer and a character as arguments. The function escapes the character based on its value according to the rules of the shell.

The function takes the following parameters:
.IB char*
A pointer to the destination buffer.
.IB int
The character to escape.

The function returns the number of bytes written to the destination buffer.

The \fBfmt_escapecharshell\fR function is intended to be used to escape characters for shell format, ensuring that strings can be safely included within shell commands.

.SH EXAMPLES
The following example demonstrates how to use the \fBfmt_escapecharshell\fR function to escape characters for shell format:

.nf
#include <stdio.h>
#include <lib/fmt.h>

int main() {
    char dest[20];
    int c = '"';

    size_t written = fmt_escapecharshell(dest, c);

    printf("Written %d bytes: %s\n", written, dest);

    return 0;
}
.nef