.TH uint16_read 3
.SH NAME
uint16_read \- read a little-endian 16-bit integer
.SH SYNTAX
.B #include "uint16.h"
.LP
uint16 \fBuint16_read\fP(const char* \fIin\fP);
.SH DESCRIPTION
.B uint16_read
reads two bytes from the memory pointed to by \fIin\fP and interprets them
as a little-endian 16-bit unsigned integer.
.SH SEE ALSO
uint16(3)