.Dd March 31, 2025
.Dt PATH_IS_DIRECTORY 3
.Os
.Sh NAME
.Nm path_is_directory
.Nd check if a path refers to a directory
.Sh SYNOPSIS
.In path.h
.Ft int
.Fn path_is_directory "const char *p"
.Sh DESCRIPTION
The
.Fn path_is_directory
function checks whether the path
.Fa p
exists and points to a directory.
.Sh RETURN VALUES
Returns non-zero if
.Fa p
is a directory, or 0 otherwise.
.Sh SEE ALSO
.Xr path_exists 3