.Dd March 31, 2025
.Dt PATH_EXISTS 3
.Os
.Sh NAME
.Nm path_exists
.Nd check if a file or directory exists
.Sh SYNOPSIS
.In path.h
.Ft int
.Fn path_exists "const char *p"
.Sh DESCRIPTION
The
.Fn path_exists
function checks whether a file or directory at path
.Fa p
exists on the filesystem.
.Sh RETURN VALUES
Returns non-zero if the path exists, or 0 otherwise.
.Sh SEE ALSO
.Xr path_access 3 ,
.Xr path_is_directory 3