.TH PATH_SKIPS 3 "15 Mar 2023" "CB" "Library Functions"

.SH NAME
path_skips \- Skip non-directory separators in a path

.SH SYNOPSIS
.IB #include <lib/path_internal.h>
.IB #include <lib/utf8.h>

.IB size_t
.IB path_skips(const char* s);

.SH DESCRIPTION
The \fBpath_skips\fR function skips non-directory separators in a given path. It returns the number of characters skipped.

.SH ARGUMENTS
.TP
.IB s
The input path string.

.SH RETURN VALUE
The function returns the number of characters skipped.

.SH EXAMPLES
The following example demonstrates how to use the \fBpath_skips\fR function:

.nf
#include <stdio.h>
#include <lib/path_internal.h>
#include <lib/utf8.h>

int main() {
    const char* path = "/usr/lib/bin";
    size_t skipped = path_skips(path);
    printf("Skipped non-separator length: %zu\n", skipped);
    return 0;
}
.nef

.SH SEE ALSO
.IB path_issep,
.IB u8_len