.Dd March 31, 2025
.Dt PATH_FIND 3
.Os
.Sh NAME
.Nm path_find
.Nd find a file inside a directory
.Sh SYNOPSIS
.In path.h
.Ft int
.Fn path_find "const char *path" "const char *name" "stralloc *out"
.Sh DESCRIPTION
The
.Fn path_find
function searches the directory specified by
.Fa path
for an entry matching
.Fa name .
If found, the full path to the entry is appended to
.Fa out .
.Sh RETURN VALUES
Returns 1 if the file was found, or 0 otherwise.