if(USE_ZLIB)
  if(NOT ZLIB_LIBRARY)
    pkg_search_module(ZLIB zlib libz z)
    if(ZLIB_FOUND)
      if(pkgcfg_lib_ZLIB_z)
        set(ZLIB_LIBRARY "${pkgcfg_lib_ZLIB_z}" CACHE FILEPATH "")
      endif(pkgcfg_lib_ZLIB_z)
    else(ZLIB_FOUND)
      # include(FindZlib)
    endif(ZLIB_FOUND)
  endif(NOT ZLIB_LIBRARY)

  if(NOT ZLIB_LIBRARY)

    message(STATUS "Checking for libz")
    find_library(ZLIB_LIBRARY z)
    if(ZLIB_LIBRARY)
      message(STATUS "Found libz: ${ZLIB_LIBRARY}")
      set(ZLIB_FOUND TRUE)
      if(ZLIB STREQUAL "")
        set(ZLIB z)
      endif(ZLIB STREQUAL "")

    endif(ZLIB_LIBRARY)
  endif(NOT ZLIB_LIBRARY)
  if(ZLIB_LIBRARY)
    message(STATUS "zlib library found: ${ZLIB_LIBRARY}")
  endif(ZLIB_LIBRARY)
  message("ZLIB_LIBRARY = ${ZLIB_LIBRARY}")

else(USE_ZLIB)
  unset(ZLIB_LIBRARY CACHE)
endif(USE_ZLIB)
