macro(check_msys_cygwin_mingw)
  file(WRITE "${CMAKE_BINARY_DIR}/cmake/try-msys.c" # include <stdio.h>\n\n#ifndef __MSYS__\n#error \"Not MSYS\"\n#endif\n\nint main() {\n\tprintf(\"OK\\n\");\n\treturn 0;\n}\n"
       )
  file(WRITE "${CMAKE_BINARY_DIR}/cmake/try-mingw.c" "#include <stdio.h>\n\n#ifndef __MINGW32__\n#ifndef __MINGW64__\n#error \"Not MINGW\"\n#endif\n#endif\n\nint main() {\n\tprintf(\"OK\\n\");\n\treturn 0;\n}\n")
  file(WRITE "${CMAKE_BINARY_DIR}/cmake/try-cygwin.c" "#include <stdio.h>\n\n#ifndef __CYGWIN__\n#error \"Not CYGWIN\"\n#endif\n\nint main() {\n\tprintf(\"OK\\n\");\n\treturn 0;\n}\n")
  set(SYS "")

  try_compile(TRY_MSYS "${CMAKE_BINARY_DIR}/cmake" ${CMAKE_BINARY_DIR}/cmake/try-msys.c)
  if(TRY_MSYS)
    set(MSYS TRUE CACHE BOOL "System is Msys")
    set(SYS msys)
  else(TRY_MSYS)
    try_compile(TRY_CYGWIN "${CMAKE_BINARY_DIR}/cmake" ${CMAKE_BINARY_DIR}/cmake/try-cygwin.c)
    if(TRY_CYGWIN)
      set(CYGWIN TRUE CACHE BOOL "System is Cygwin")
      set(SYS cygwin)
    else(TRY_CYGWIN)
      try_compile(TRY_MINGW "${CMAKE_BINARY_DIR}/cmake" ${CMAKE_BINARY_DIR}/cmake/try-mingw.c)
      if(TRY_MINGW)
        set(MINGW TRUE CACHE BOOL "System is Cygwin")
        set(SYS mingw)
      else(TRY_MINGW)

      endif(TRY_MINGW)
    endif(TRY_CYGWIN)
  endif(TRY_MSYS)

  message(STATUS "System detected: ${SYS}")
  set(SYSTEM "${SYS}" PARENT_SCOPE)
  try_compile(TRY_MINGW "${CMAKE_BINARY_DIR}/cmake" ${CMAKE_BINARY_DIR}/cmake/try-mingw.c)
endmacro(check_msys_cygwin_mingw)
