if(USE_BZIP)
  message(CHECK_START "Checking for bzip2 library")

  pkg_search_module(BZIP2 libbz2 bzip2 QUIET)
  if(NOT BZIP2_FOUND OR "${BZIP2_FOUND}" STREQUAL "")

    find_library(BZIP2_LIBRARY NAMES bz2)
    if(BZIP2_LIBRARY)
      set(BZIP2_FOUND TRUE)
    endif(BZIP2_LIBRARY)

  else(NOT BZIP2_FOUND OR "${BZIP2_FOUND}" STREQUAL "")

    if(pkgcfg_lib_BZIP2_bz2)
      set(BZIP2_LIBRARY ${pkgcfg_lib_BZIP2_bz2})
    else(pkgcfg_lib_BZIP2_bz2)
      if(BZIP2_LIBRARIES)
        set(BZIP2_LIBRARY ${BZIP2_LIBRARIES})
      else(BZIP2_LIBRARIES)
        set(BZIP2_LIBRARY bz2)
      endif(BZIP2_LIBRARIES)
    endif(pkgcfg_lib_BZIP2_bz2)
    set(BZIP2_LINK_LIBRARY ${pkgcfg_lib_BZIP2_bz2} ${BZIP2_LINK_LIBRARIES})
    set(BZIP2_INCLUDE_DIR ${BZIP2_INCLUDE_DIRS})
    set(BZIP2_LIBRARY_DIR ${BZIP2_LIBRARY_DIRS})
  endif(NOT BZIP2_FOUND OR "${BZIP2_FOUND}" STREQUAL "")

  if(BZIP2_FOUND)
    message(CHECK_PASS "found")
  else(BZIP2_FOUND)
    message(CHECK_FAIL "NOT found")
  endif(BZIP2_FOUND)

else(USE_BZIP)
  unset(BZIP2_LDFLAGS CACHE)
  unset(BZIP2_STATIC_LDFLAGS CACHE)
endif(USE_BZIP)
