option(PROFILER_GPROF "Generate gprof instrumentation" OFF)

if(PROFILER_GPROF)
  set(CMAKE_C_FLAGS "-pg ${CMAKE_C_FLAGS}")
  set(CMAKE_CXX_FLAGS "-pg ${CMAKE_CXX_FLAGS}")

  set(CMAKE_EXE_LINKER_FLAGS "-pg ${CMAKE_EXE_LINKER_FLAGS}")
  set(CMAKE_SHARED_LINKER_FLAGS "-pg ${CMAKE_SHARED_LINKER_FLAGS}")
endif(PROFILER_GPROF)
