.TH MMAP_PRIVATE_FD 3
.SH NAME
mmap_private_fd \- create a private memory mapping of a file
.SH SYNOPSIS
.B #include "mmap.h"
.PP
.BI "char* mmap_private_fd(fd_type " fd ", size_t* " filesize ");"
.SH DESCRIPTION
.B mmap_private_fd
maps the entirety of the file descriptor
.I fd
into memory as a private, read-write mapping. The size of the file is stored in
.I filesize
upon success.
.SH RETURN VALUE
Returns a pointer to the mapped memory on success, or NULL on failure.